WIP: Feature/admin page
proepidesenvolvimento/guardioes-web pull request #150
Opened 2020-11-19 04:39 UTC by emanuks

This PR adds the admin page (#117 - @emanuks). 
This PR is associated with this API branch: https://github.com/proepidesenvolvimento/guardioes-api/tree/feature/adminMethods.

2020-11-19 04:40 UTC, emanuks commented
There's an error happening that any 'GET' requisition in this page returns 401.

2020-11-23 23:01 UTC, ViniciusPuerto requested changes

2020-11-23 23:01 UTC, ViniciusPuerto commented on src/pages/Home/components/Admins/services/deleteAdmin.js
> +    await api.delete(`/admin/${id}`, {
A rota de admin tem q ser no plural `await api.delete(`/admins/${id}`, {`

2020-11-24 01:06 UTC, ViniciusPuerto approved these changes

2020-11-24 01:07 UTC, merged