criação de componentes, testes e resolução de alguns warnings
ProEpiDesenvolvimento/guardioes-web pull request #329
Opened 2021-11-11 19:12 UTC by robsonramon

2021-11-24 15:49 UTC, alvesitalo reviewed
Único detalhe é o warning de 
`./node_modules/jest-circus/node_modules/jest-util/build/requireOrImportModule.js
Critical dependency: the request of a dependency is an expression`

Mas parece ser da própria biblioteca, pode confirmar @robsonramon?

2021-11-24 16:19 UTC, robsonramon commented
Aparentemente está relacionado com a versão do request do NPM e parece não ser um problema em si, mas posso atualizar a versão e ver se resolve este warning.

2021-12-02 16:18 UTC, jps12 requested changes
Na tela de login não aparece o erro quando o usuário erra a senha. O esperado era que ficasse vermelho como sinal de alerta

2021-12-02 19:30 UTC, jps12 approved these changes

2021-12-02 21:43 UTC, alvesitalo approved these changes

2021-12-02 21:43 UTC, merged