Fix/edit users
ProEpiDesenvolvimento/guardioes-web pull request #333
Opened 2021-12-18 22:03 UTC by EduardoMdR

## O que foi realizado
- A issue #327 
- Edição de usuário agora está correta

## O que poderia ser implementado
- Adicionar mais dados para serem visualizados e editados (mas resolvi esperar uma review para ver se isso é necessário)

closes #327

2021-12-22 23:10 UTC, alvesitalo commented on src/pages/Home/components/Users/index.js
> +          label="Código identificador"
Renomeie a label para "Código de Identificação"

2021-12-22 23:11 UTC, alvesitalo commented on src/pages/Home/components/Users/index.js
> +          value={userShow.is_professional == false ? "Não" : "Sim"}
Troca a lógica de value para `userShow.is_professional ? "Sim" : "Não"`. Isso cobre os casos onde o valor seja null ou undefined.

2021-12-22 23:15 UTC, alvesitalo commented on src/pages/Home/components/Users/index.js
> +          label="Aniversário"
Renomeie a label para "Data de Nascimento"

2021-12-22 23:17 UTC, alvesitalo commented on src/pages/Home/components/Users/index.js
> +          value={moment(userShow.birthdate).format('MM/DD/YYYY')}
Mude o formato da data para DD/MM/YYYY

2021-12-22 23:21 UTC, alvesitalo requested changes
A edição está funcionando legal. Só alguns pontos além do que foi comentado: 
1. Troca o título de "User Information" para "Informações do Usuário" na modal de Visualizar;
2. Coloca os campos dela na mesma ordem da modal de Editar, com o "Código identificador" e a "Data de criação" por último nessa mesma ordem;
3. Na modal de Visualizar também está faltando o campo de Nome.

2021-12-28 20:34 UTC, EduardoMdR commented
Todas as solicitações foram corrigidas

2021-12-29 02:19 UTC, alvesitalo approved these changes
Ficou ótimo 😄

2021-12-29 02:20 UTC, merged